language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - phpunit --coverage-text
